[module/cpuLabel]
format-background=${colors.primary}
type = custom/script
exec = echo " "
interval = 1000



[module/cpuUtil]
format-background=${colors.primary}
type = internal/cpu
interval = 2
label = %percentage%%
click-left = exec top


[module/cpuTemp]
format-background=${colors.primary}
type = internal/temperature
thermal-zone = 0

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}



label = %temperature-c:3%

; this one was the temp and usage all in one :O
[module/cpu]
format-background=${colors.primary}
type=custom/script

interval=2
exec="$HOME/.config/polybar/scripts/cpu.sh 2>/dev/null"
label =  %output:12:12%
