[module/fs]
format-background=${colors.primary}
type = internal/fs

mount-0 = /
; mount-1 = /mnt/c/
; mount-3 = /mnt/d/

label-mounted =  %percentage_free%% of %total%
label-unmounted =  %mountpoint%: not mounted
