[gpuClick]
click-left= "exec kitty watch -n 1 nvidia-smi"

[module/gpuLabel]
format-background=${colors.primary}
inherit = gpuClick
type = custom/script
interval = 1000
exec = echo G:


[module/gpuUtil]
format-background=${colors.primary}
inherit = gpuClick
type = custom/script
exec = nvidia-smi -q -d UTILIZATION | grep Gpu | grep -o '[0-9]*'
interval = 5
label = %output%%


[module/gpuTemp]
format-background=${colors.primary}
inherit = gpuClick
type = custom/script
exec = nvidia-smi stats -d temp -c 1 | grep -o '[0-9]*$'
interval = 5
label = %output%°


[module/vramLabel]
format-background=${colors.primary}
inherit = gpuClick
type = custom/script
exec = echo VRAM:
interval = 1000


[module/vramPercent]
format-background=${colors.primary}
inherit = gpuClick
; idk how to do this one but it would be neat

[module/vramUsed]
format-background=${colors.primary}
inherit = gpuClick
type = custom/script
exec = nvidia-settings -q UsedDedicatedGPUMemory | grep -oP '[0-9]*(?=\\.)'
interval = 5
label = %output% MB


[module/gpu]
format-background=${colors.primary}
type = custom/script
exec = "$HOME/.config/polybar/scripts/gpu.sh 2>/dev/null"
interval = 5

label = GPU: %output:16:16%
