[module/net]
format-background=${colors.primary}


type = internal/network
; Name of the network interface to display. You can get the names of the
; interfaces on your machine with `ip link`
; Wireless interfaces often start with `wl` and ethernet interface with `eno` or `eth`
interface = enp0s31f6

; Seconds to sleep between updates
; Default: 1
interval = 3.0


; Consider an `UNKNOWN` interface state as up.
; Some devices like USB network adapters have 
; an unknown state, even when they're running
; Default: false
unknown-as-up = true

label-connected =  %upspeed:12:12%, %downspeed:12:12%

label-disconnected =  not connected
