[module/spotify]
format-background=${colors.primary}
type = custom/script
interval = 1
format-prefix = " "
format = <label>
exec = python ~/.config/polybar/modules/spotify_status/spotify_status.py -f '{song} - {artist}{play_pause} ' -p ', (Paused)' -t 64
;control players (optional)
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous 