; this is just to update the label of the switchWallpaper module when the user scrolls over it
; BUT IT DOESNT WORK :(

[module/updates_ipc]
format-background=${colors.primary}
type = custom/ipc

hook-0 = ~/.config/polybar/scripts/switchWallpaper.sh query
label=ipc
initial=1

click-left = polybar-msg hook updates_ipc 1