[module/switchWallpaper]
format-background=${colors.primary}
type = custom/script
format =  <label>
exec = ~/.config/polybar/scripts/switchWallpaper.sh query
interval = 1
label = %output%


click-left=~/.config/polybar/scripts/switchWallpaper.sh menu

scroll-up = ~/.config/polybar/scripts/switchWallpaper.sh prev
            ; && polybar-msg hook updates_ipc 1
scroll-down = ~/.config/polybar/scripts/switchWallpaper.sh next
            ; && polybar-msg hook updates_ipc 1

; exec = polybar-msg hook updates_ipc 1