

; the `time` and `date` modules are intended to be used together, with a 0 px gap between them
; that way you can click on one and have it switch to long/short formats independetly of the other

[module/time]
format-background=${colors.primary}
type = internal/date
interval = 1
time = "%l:%M"
time-alt = "%I:%M:%S %P"
format = <label>

format-padding = 1
label =  %time%, 

[module/date]
format-background=${colors.primary}
type = internal/date
internal = 1
time = %b %d
time-alt =%A, %B %d, %Y
format = <label>

format-padding = 1 
label = %time%


; for when you don't have a 0px gap between them: 
[module/dateTime]
format-background=${colors.primary}
type = internal/date
interval = 1
time = "%l:%M"
time-alt = "%A, %b %e at %l:%M:%S"
label-active-font = 3

label =  %time%


;minimal clock
[module/timeOnly]
format-background=${colors.primary}
type = custom/script
interval = 1
exec = "date '+%-I:%M'"
label = %output%
format-padding = 2