

; uses https://github.com/chubin/wttr.in

[module/weatherCondition]
format-background=${colors.primary}
type = custom/script
interval = 1800
exec = curl -s 'wttr.in/?format=%C' 
label =  %output%

[module/weatherTemperatureF]
format-background=${colors.primary}
type = custom/script
interval = 1800
exec = curl -s 'wttr.in/?format=%t' | grep -o '[^+]*'

label =  %output%

[module/weather]
format-background=${colors.primary}
type = custom/script
interval = 1800
exec = $HOME/.config/polybar/scripts/weather.sh

click-left=kitty -o remember_window_size=no -o initial_window_width=1038 -o initial_window_height=1200 zsh -c "curl 'v2d.wttr.in/?T'; read"
label = %output%