[module/xwindow]
format-background=${colors.primary}
type = internal/xwindow
label = %title:0:30:...%

label-mode-padding = 6
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-underline = #fba922
label-focused-background = #000000
label-focused-padding = 6

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 6

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 6

; Separator in between workspaces
label-separator = |