#!/usr/bin/env zsh

# Boilerplate code generator to quickly get something started
# Uses associative arrays
# (https://unix.stackexchange.com/a/702297)

typeset -A STARTERS=(
  # <label> <command>
  'node-typescript' 'pnpm dlx @cjcarrick/ts-cli'
  'vite-fullstack' 'git clone https://github.com/cjcarrick/vite-fullstack'
)

KEY=$(printf '%s\n' "${(@k)STARTERS}" | fzf)

# catch the user quitting fzf
[[ -z "$CMD" ]] && exit 0 

CMD="$STARTERS[$KEY]"
echo "$KEY: $CMD"
sh -c "$CMD"

