#!/usr/bin/env zsh

COLORSDIR=~/.config/alacritty/colors/
COLORSFILE=~/.config/alacritty/colors.yml

if [[ ! -e $COLORSFILE ]]; then
  return 1
fi

# Save current colorscheme in case user aborts
BACKUP="${TMPDIR}colorscheme.bak"
cp $COLORSFILE $BACKUP

RESULT=$(fd . $COLORSDIR -t f -x realpath --relative-to=$COLORSDIR | fzf --preview="cp ${COLORSDIR}{} $COLORSFILE && bat $COLORSFILE")

if [[ -z $RESULT ]]; then
  mv $BACKUP $COLORSFILE
fi

