#!/usr/bin/env zsh

sdcv $@ \
  | sed \
    -e "s/\[/[90m[/g" \
    -e "s/]/][0m/g" \
    -e "s/{/[36m/g" \
    -e "s/}/[0m/g" \
    -e "s/\.  /. /g" \
    -e "s/^-->\(.*\)/[90;3m--> \1[0m/g" \
  | less -r
