icons_format = "none"

[theme]
theme = "plain"
[theme.overrides]
separator = ""
idle_fg = "#ffffff"
good_fg = "#ffffff"
warning_fg = "#ffffff"

[[block]]
block = "net"
format = "{WIFI: $ssid|ETH:} $device at $ip "

[[block]]
block = "cpu"
format = "╎ CPU: $frequency.eng(3,_Hz,!G) $utilization.eng(4) "
[[block]]
block = "temperature"
format ="$average.eng(4) "

[[block]]
block = "memory"
format = "╎ MEM: $mem_used.eng(4,_B) "
format_alt = "╎ MEM: $mem_used.eng(4,_B) of $mem_total.eng(4,_B), SWAP: $swap_used.eng(4,_B) of $swap_total.eng(3,_B) "
interval = 10

[[block]]
block = "nvidia_gpu"
interval = 1
format = "╎ GPU: $clocks.eng(4,_Hz,!M) $utilization.eng(4) $temperature.eng(4) "

[[block]]
block = "nvidia_gpu"
interval = 1
format = "╎ VRAM: $memory.eng(5,_B) "

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
alert_unit = "GB"
interval = 20
format = "╎ /: $used.eng(4,_B) "

[[block]]
block = "time"
interval = 1
[block.format]
short = "╎ %A, %b %-e %-I:%M "
full = "╎ %A, %b %-e %-I:%M:%S "
