icons_format = "none"

[theme]
theme = "plain"
[theme.overrides]
separator = ""
idle_fg = "#ffffff"
good_fg = "#ffffff"
warning_fg = "#ffffff"

[[block]]
block = "net"
format = "{WIFI: $ssid|ETH:} $device at $ip "

[[block]]
block = "cpu"
format = "╎ CPU: $frequency.eng(w:3, p:G, hide_unit:true) $utilization.eng(w:4) "
[[block]]
block = "temperature"
format ="$average.eng(w:4) "

[[block]]
block = "memory"
format = "╎ MEM: $mem_used.eng(w:4, p:G, hide_unit:true) "
format_alt = "╎ MEM: $mem_used.eng(w:4, p:G, hide_unit:true, hide_prefix:true)/$mem_total.eng(w:4, p:G, hide_unit:true, hide_prefix:true), SWAP: $swap_used.eng(w:4, p:G, hide_unit:true, hide_prefix:true)/$swap_total.eng(w:3, p:G, hide_unit:true, hide_prefix:true) "
interval = 10
 
[[block]]
block = "nvidia_gpu"
interval = 1
format = "╎ GPU: $clocks.eng(w:4, p:M, hide_unit:true) $utilization.eng(w:4) $temperature.eng(w:4) "

[[block]]
block = "nvidia_gpu"
interval = 1
format = "╎ VRAM: $memory.eng(w:5, hide_unit:true) "

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
alert_unit = "GB"
interval = 20
format = "╎ /: $used.eng(w:4, hide_unit:true) "

[[block]]
block = "time"
interval = 1
[block.format]
short = "╎ $timestamp.datetime(f:'%A, %b %-e %-I:%M') "
full = "╎ $timestamp.datetime(f:'%A, %b %-e %-I:%M:%S') "
